using System.Data;
using System.Data.SQLite;
using System;
using System.Diagnostics;
using System.Windows.Forms;
using System.Collections.Generic;

namespace timelord
{
    /// <summary>
    /// A generic SQLite Connection manager class
    /// </summary>
    /// <remarks>
    /// This class makes use of Lambda expressions and Delegates
    /// </remarks>
    public class SQLiteInstance
    {
        private readonly string PathToDatabase;

        public SQLiteInstance(string pathToDatabase, List<string> createQueries)
        {
            this.PathToDatabase = pathToDatabase;

            // Execute each create query
            ExecuteAction(c =>
            {
                foreach(string createQuery in createQueries)
                {
                    ExecuteVoidStatement(c, createQuery);
                }
            });
        }

        private SQLiteConnection GetConnection()
        {
            return new SQLiteConnection("Data Source=" + PathToDatabase + ";Version=3;");
        }

        /// <summary>
        /// This method executes and passes a <c>SQLiteConnection</c> to a void method.
        /// </summary>
        /// <param name="action">The function to execute.</param>
        private void ExecuteAction(Action<SQLiteConnection> action)
        {
            using (SQLiteConnection c = GetConnection())
            {
                c.Open();
                action(c);
            }
        }

        /// <summary>
        /// This method executes and passes a <c>SQLiteConnection</c> to a generic method.
        /// </summary>
        /// <typeparam name="T">The generic DataType to return from the function.</typeparam>
        /// <param name="function">The function to execute.</param>
        /// <returns></returns>
        private T ExecuteFunction<T>(Func<SQLiteConnection,T> function)
        {
            using (SQLiteConnection c = GetConnection())
            {
                c.Open();
                return function(c);
            }
        }

        private void ExecuteVoidStatement(SQLiteConnection c, string databaseCreateQuery)
        {
            using (SQLiteCommand cmd = c.CreateCommand())
            {
                cmd.CommandText = databaseCreateQuery;
                cmd.ExecuteNonQuery();
            }
        }

        /// <summary>
        /// Gets a standard SQLite table assuming it has a primary key of id 
        /// </summary>
        /// <returns>A datatable containing the table from the SQLite database.</returns>
        public DataTable GetTable(string tableName, string selectQuery)
        {
            return ExecuteFunction(c =>
            {
                using (SQLiteDataAdapter adapter = new SQLiteDataAdapter(selectQuery, c))
                {
                    DataTable dt = new DataTable(tableName);
                    adapter.Fill(dt);
                    // set primary key
                    dt.PrimaryKey = new DataColumn[] { dt.Columns["id"] };
                    // allow null for autogenerated field
                    dt.Columns["id"].AllowDBNull = true;

                    return dt;
                }

            });
        }

        /// <summary>
        /// Commits a datatable to the sqlite database
        /// </summary>
        /// <param name="table">The datatable to commit</param>
        public void Commit(DataTable table, string selectTaskQuery)
        {
            // Execute a void action that needs a database connection
            ExecuteAction(c =>{

                using (SQLiteDataAdapter adapter = new SQLiteDataAdapter(selectTaskQuery, c))
                {
                    using (SQLiteCommandBuilder builder = new SQLiteCommandBuilder(adapter))
                    {
                        adapter.UpdateCommand = builder.GetUpdateCommand();
                        adapter.DeleteCommand = builder.GetDeleteCommand();
                        adapter.InsertCommand = builder.GetInsertCommand();

                        adapter.RowUpdated += DataAdapter_RowUpdated;

                        adapter.Update(table);
                    }
                }
            });
        }

        /// <summary>
        /// This method is called every time a row is updated and stores the insert id into the DataTable.
        /// </summary>
        private void DataAdapter_RowUpdated(object sender, System.Data.Common.RowUpdatedEventArgs e)
        {
            if (e.Status == UpdateStatus.Continue && e.StatementType == StatementType.Insert)
            {
                e.Row["id"] = ( (SQLiteConnection) e.Command.Connection).LastInsertRowId;
                e.Row.AcceptChanges();
            }
        }

    }
}
